### ISSUE TITLE
Factory attributes

### ISSUE THREAD

**Issue by jorgebodega** [foliveirafilho/typeorm-seeding-cli-error#1]
In the file `src/user.factory.ts` the `entity` and the `dataSource` should be like this:

```diff
import { faker } from '@faker-js/faker';
import { Constructable, FactorizedAttrs, Factory } from '@jorgebodega/typeorm-factory';
- import { DataSource } from 'typeorm';
+ import { DbDataSource } from './data-source';
import { UserEntity } from './user.entity';

export class UserFactory extends Factory<UserEntity> {
- protected entity: Constructable<UserEntity>;
+ protected entity = UserEntity;

- protected dataSource: DataSource;
+ protected dataSource = DbDataSource;

  protected attrs(): FactorizedAttrs<UserEntity> {
    return {
      fullName: faker.name.fullName(),
      email: faker.internet.email(),
    };
  }
}
```

Can you check if that works?

**Comment by foliveirafilho** [comment]
The error stays the same as before, even with the modifications you shown. I've pushed in the repo if you would like to see what's going on.

But I've changed the `entity` declaration in my original repo that the previous issue refers to like you provided:
```diff
- protected entity: UserEntity;
+ protected entity = UserEntity;
```

And it worked! Is it normal behavior? I didn't quite follow.

**Comment by jorgebodega** [comment]
It is.

The entity class must be provided in order to create the instances, as every `create` or `make` operation should work with different ones.

If you have any suggestion on how to improve the docs, you are welcome to create a PR.

Does this fix the original issue?

**Comment by foliveirafilho** [comment]
Yes, it does. I'll comment on the previous issue so it can be closed properly. Thank you very much for your help.

If I manage to find some time, I'll try to improve the docs.
